[project]
name = "pdf-analyzer"
version = "0.1.0"
description = "Provides an analysis of pdf files and which packages are best used"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pdfplumber>=0.9.0",
    "pymupdf>=1.23.0",
    "pypdf>=3.0.0",
    "tqdm>=4.65.0",
]
